//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoType { get; set; }
        public int JobId { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
